name: IP Ready Scans
on: [push]

jobs:
  checkmarx_scan:
    uses: CognizantCodeHub/IPReady_workflows/.github/workflows/checkmarx_scan.yml@Rel-1.0
    with:
      ProjectName: ${{ github.event.repository.name }}
    secrets: inherit

  blackduck_scan:
    name: Blackduck Scan
    if: startsWith(github.ref, 'refs/heads/oss/')
    runs-on: self-hosted-ubuntu-cdhb
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        gradle-version: '8.4'
    - name: building 
      run: |
        chmod +x ./gradlew
        ./gradlew build
    - name: Blackduck Scan  
      uses: CognizantCodeHub/IPReady_workflows/blackduck/generic@Rel-1.0
      with:
          ProjectName: ${{ github.event.repository.name }}
          SYNOPSIS_URL: ${{ secrets.SYNOPSIS_URL }}
          BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
          BLACKDUCK_TOKEN: ${{ secrets.BLACKDUCK_TOKEN }}

  sonarqube_scan:
    name: SonarQube Scan
    if: startsWith(github.ref, 'refs/heads/sonar/')
    runs-on: self-hosted-ubuntu-cdhb
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: building
        run: |
          chmod +x ./gradlew
          ./gradlew test
      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ github.event.repository.name }} \
            -Dsonar.sources=. \
            -Dsonar.java.binaries=.\
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            
            
